"""add number and address columns

Revision ID: a658a0b477ed
Revises: 2750203965b4
Create Date: 2024-07-30 16:01:05.726880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a658a0b477ed'
down_revision = '2750203965b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(length=256), nullable=True))
        batch_op.alter_column('wishlist',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=120),
               existing_nullable=True)
        batch_op.alter_column('cart',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=120),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_user_address'), ['address'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_number'), ['number'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_number'))
        batch_op.drop_index(batch_op.f('ix_user_address'))
        batch_op.alter_column('cart',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=256),
               existing_nullable=True)
        batch_op.alter_column('wishlist',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=256),
               existing_nullable=True)
        batch_op.drop_column('address')
        batch_op.drop_column('number')

    # ### end Alembic commands ###
