"""add wishlist column to user

Revision ID: b781a400e20f
Revises: 9cb7aaefac95
Create Date: 2024-05-28 22:58:00.221782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b781a400e20f'
down_revision = '9cb7aaefac95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wishlist', sa.String(length=256), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_lastName'), ['lastName'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_wishlist'), ['wishlist'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_wishlist'))
        batch_op.drop_index(batch_op.f('ix_user_lastName'))
        batch_op.drop_column('wishlist')

    # ### end Alembic commands ###
